### ISSUE TITLE
Timeline: Menu and header information disappears on the timeline node detail page.

### ISSUE THREAD

**Issue by vincentmartens** [GettyScholarsWorkspace/GettyScholarsWorkspace#10]
**Previous Ticket, by KC:**

1. Go to the SW test site
2. Login in as admin
3. Click into any project
4. Click Timeline in the nav
5. Click "Add New Timeline Event"
6. Fill out all the required information and click save.
7. Observe the node page

**Bug:**

The navigation and most of the header items do not display. (ex: http://grivmkh.getty.edu/workspace-test/node/3376)

**Screenshot:**

<img width="1367" alt="screen shot 2015-12-16 at 5 03 08 pm" src="https://cloud.githubusercontent.com/assets/14829303/12935515/0698edc6-cf4b-11e5-95ec-c411314af5ed.png">

**Comment by myardleyc** [comment]
Node detail removed for all users except the author of that page in GSW 1.1.
